1. **Array Creation**: Create a 1D NumPy array containing the numbers from 0 to 9. Then reshape it into a 2D array with 2 rows and 5 columns.

In [14]:
import numpy as np
one_d = np.array([0,1,2,3,4,5,6,7,8,9])
print(one_d)
two_d = one_d.reshape((2,5))
print(two_d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
import numpy as np

# Create a 1D NumPy array containing numbers from 0 to 9
array_1d = np.arange(10)

# Reshape it into a 2D array with 2 rows and 5 columns
array_2d = array_1d.reshape(2, 5)

array_2d


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

2. **Array Operations**: Given two NumPy arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])`, perform the following operations:
   - Add the two arrays.
   - Multiply the two arrays element-wise.
   - Find the dot product of the two arrays.

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1. Add the two arrays
addition = a + b

# 2. Multiply the two arrays element-wise
elementwise_multiplication = a * b

# 3. Find the dot product of the two arrays
dot_product = np.dot(a, b)

addition, elementwise_multiplication, dot_product


(array([5, 7, 9]), array([ 4, 10, 18]), 32)


3. **Statistical Functions**: Create a NumPy array of 100 random numbers between 0 and 1. Calculate the mean, median, and standard deviation of the array.

In [6]:
random_array = np.random.rand(100) #Generates random numbers from a uniform distribution over the interval [0, 1).
print(random_array)

# Calculating the mean, median, and standard deviation
mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

mean_value, median_value, std_deviation


[0.37959614 0.86112176 0.67895564 0.93802119 0.77479677 0.26439765
 0.78488118 0.16202867 0.50464092 0.08335267 0.23934959 0.62631186
 0.4390085  0.052486   0.87671591 0.21307172 0.37285582 0.36783789
 0.08871647 0.57689853 0.47447069 0.47351942 0.5081831  0.26810705
 0.2835592  0.78128595 0.08887484 0.13893163 0.00983362 0.31806977
 0.82170753 0.83286749 0.02629985 0.86256097 0.67232522 0.21858889
 0.01071869 0.25503607 0.55227366 0.89511843 0.53498381 0.89813568
 0.20912791 0.55739423 0.37174524 0.58423901 0.6524169  0.11870669
 0.92240669 0.36817685 0.98928788 0.96744738 0.12026853 0.52870615
 0.90462728 0.11101519 0.04489608 0.27478942 0.29144686 0.90607496
 0.51754797 0.42131502 0.28391851 0.3687399  0.59091034 0.53558695
 0.58442416 0.92960084 0.73578399 0.46582462 0.73888028 0.63966488
 0.76286701 0.29896225 0.35411567 0.77698722 0.6153649  0.70136795
 0.75345607 0.72186141 0.18647497 0.76695183 0.75654023 0.43420496
 0.15562462 0.17094639 0.51831598 0.35313456 0.14786463 0.1867

(0.48265147598353797, 0.4739950543408527, 0.2805630053040475)

4. **Boolean Indexing**: Create a NumPy array of integers from 1 to 20. Use boolean indexing to extract all even numbers from the array.

In [10]:
my_array = np.arange(1,21)
#my_even_array = [x for x in my_array if x%2 ==0]
my_even_array = my_array[my_array % 2 == 0]
my_even_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

5. **Matrix Operations**: Create two 2D NumPy arrays (3x3) and perform matrix multiplication. Verify the result using the `np.dot()` function.


In [11]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Performing matrix multiplication
matrix_multiplication = np.matmul(matrix1, matrix2)

# Verifying the result using np.dot()
dot_product_result = np.dot(matrix1, matrix2)

matrix_multiplication, dot_product_result


(array([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]),
 array([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]]))

### pandas Problems

6. **DataFrame Creation**: Create a pandas DataFrame from a dictionary containing the following data:
   ```python
   data = {
       'Name': ['Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35],
       'City': ['New York', 'Los Angeles', 'Chicago']
   }
   ```
   Display the DataFrame.


In [19]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

my_df = pd.DataFrame(data)
my_df


Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

7. **DataFrame Indexing**: Using the DataFrame created in the previous problem, select the 'Name' and 'City' columns and display the result.

In [26]:
selected = my_df[['Name', 'City']]
selected

Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

8. **Filtering Data**: Given the following DataFrame:
   ```python
   import pandas as pd

   data = {
       'Product': ['A', 'B', 'C', 'D'],
       'Price': [100, 150, 200, 250],
       'Stock': [30, 20, 0, 15]
   }
   df = pd.DataFrame(data)
   ```
   Filter the DataFrame to show only products that are in stock (Stock > 0).

In [27]:
data = {
    'Product': ['A', 'B', 'C', 'D'],
    'Price': [100, 150, 200, 250],
    'Stock': [30, 20, 0, 15]
}

df = pd.DataFrame(data)
df

Product  Price  Stock
0       A    100     30
1       B    150     20
2       C    200      0
3       D    250     15

In [28]:
# Filtering the DataFrame to show only products that are in stock (Stock > 0)
df_in_stock = df[df['Stock'] > 0]
df_in_stock

Product  Price  Stock
0       A    100     30
1       B    150     20
3       D    250     15

9. **Group By**: Create a DataFrame with the following data:
   ```python
   data = {
       'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
       'Points': [10, 20, 15, 25, 30, 10]
   }
   ```
   Group the DataFrame by 'Team' and calculate the total points for each team.

In [37]:
data = {
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Points': [10, 20, 15, 25, 30, 10]
}
df = pd.DataFrame(data)

# Grouping the DataFrame by 'Team' and calculating the total points for each team
team_points = df.groupby('Team').sum().reset_index()

team_points

Team  Points
0    A      30
1    B      40
2    C      40

10. **CSV File Handling**: Write a pandas DataFrame to a CSV file named `students.csv` with the following data:
    ```python
    data = {
        'Student': ['John', 'Jane', 'Doe'],
        'Score': [85, 90, 78]
    }
    ```
    Then read the CSV file back into a DataFrame and display it.


In [49]:
data = {
    'Student': ['John', 'Jane', 'Doe'],
    'Score': [85, 90, 78]
}
df_students = pd.DataFrame(data)
print(df_students)
# Writing the DataFrame to a CSV file named 'students.csv'
csv_file_path = '/Users/dongwenou/Downloads/Intro to DS/HW3.csv'
df_students.to_csv(csv_file_path, index=False)


  Student  Score
0    John     85
1    Jane     90
2     Doe     78


In [48]:
# Reading the CSV file back into a DataFrame
df_students_readback = pd.read_csv(csv_file_path)
df_students_readback


Student  Score
0    John     85
1    Jane     90
2     Doe     78